### ISSUE TITLE
setup HEMIS project in your local computer 

### ISSUE THREAD

**Issue by AB-Omar** [nsia-infosys/HEMIS#6]
in order to setup HEMIS on your local computer, please follow the below steps.

1. download and install XAMPP and composer on your computer.
2. clone the project from GitHub.
3. once you have done with the cloning from GitHub, type **composer update**  in order to install all usage packages and dependencies.
4. create a database in your local server, and import the **HEMIS DATABASE**. 
note: I will share the SQL format of the database. and please import the database from your command-line rather than from phpMyAdmin in order to take less time.
5. configure .env file of the project according to your need.

in case of any issue please do not hesitate to contact me.

**Comment by braindawg** [comment]
This seems more appropriate for the Readme than an Issue - my understanding is that Issues should eventually be closed by corresponding pull requests, while this seems to be intended to live forever as a guideline for future contributors.

**Comment by AB-Omar** [comment]
it was not an issue,
